version: '3.7'

services:
  bot-discord:
    privileged: true
    build:
      dockerfile: app-dev.dockerfile
      context: .
    container_name: bot-discord
    restart: unless-stopped
    tty: true
    volumes:
      - ../../:/var/www/bot-discord
      - ./config/20-xdebug.ini:/etc/php/8.1/cli/conf.d/20-xdebug.ini
    networks:
      - bot-discord

networks:
  bot-discord:
    driver: bridge
